--Oracle Practice #1

SELECT * FROM ACDB_SECTORS;
SELECT * FROM ACDB_PACKAGES;
SELECT * FROM ACDB_CUSTOMERS;번

--Oracle Practice #2
SELECT PACK_ID, SPEED, MONTHLY_PAYMENT FROM ACDB_PACKAGES; -- 1번
SELECT 
CUSTOMER_ID, FIRST_NAME, LAST_NAME, MAIN_PHONE_NUM, SECONDARY_PHONE_NUM, PACK_ID 
FROM ACDB_CUSTOMERS; -- 2번

SELECT FIRST_NAME, LAST_NAME, PACK_ID FROM ACDB_CUSTOMERS WHERE LAST_NAME = 'King'; -- 3번
SELECT FIRST_NAME, LAST_NAME, PACK_ID, MONTHLY_DISCOUNT FROM ACDB_CUSTOMERS WHERE MONTHLY_DISCOUNT < 10; -- 4번

--Oralce Practice #3
SELECT PACK_ID, SPEED, STRT_DATE, MONTHLY_PAYMENT, MONTHLY_PAYMENT*12 AS Y_INCOME FROM ACDB_PACKAGES; -- 1번
SELECT CONCAT(CONCAT(FIRST_NAME, ' '), LAST_NAME) AS FULL_NAME, CONCAT(CONCAT(MAIN_PHONE_NUM, ', ') , SECONDARY_PHONE_NUM) AS CONTACT_DETAILS FROM ACDB_CUSTOMERS; -- 2번
SELECT FIRST_NAME AS FN, LAST_NAME AS LN, MONTHLY_DISCOUNT AS DC, CONCAT(CONCAT(CITY, ' '), STREET) AS FULL_ADDRESS FROM ACDB_CUSTOMERS; -- 3번

--Oracle Practice #4
SELECT DISTINCT CITY FROM ACDB_CUSTOMERS; -- 1번
SELECT DISTINCT CITY, STATE FROM ACDB_CUSTOMERS; -- 2번
SELECT FIRST_NAME, MONTHLY_DISCOUNT FROM ACDB_CUSTOMERS WHERE FIRST_NAME LIKE '%e';

--Oracle Practice #5
SELECT FIRST_NAME, JOIN_DATE, PACK_ID FROM ACDB_CUSTOMERS WHERE FIRST_NAME LIKE '%a%' ORDER BY PACK_ID ASC; -- 1번
SELECT FIRST_NAME, JOIN_DATE, MONTHLY_DISCOUNT, PACK_ID FROM ACDB_CUSTOMERS WHERE MONTHLY_DISCOUNT > 28 ORDER BY MONTHLY_DISCOUNT, PACK_ID ASC; -- 2번
SELECT FIRST_NAME, JOIN_DATE, MONTHLY_DISCOUNT, PACK_ID FROM ACDB_CUSTOMERS WHERE MONTHLY_DISCOUNT > 28 ORDER BY MONTHLY_DISCOUNT DESC, PACK_ID ASC; -- 3번
SELECT FIRST_NAME, JOIN_DATE, MONTHLY_DISCOUNT FROM ACDB_CUSTOMERS WHERE MONTHLY_DISCOUNT BETWEEN 28 and 30; -- 4번
SELECT FIRST_NAME, JOIN_DATE FROM ACDB_CUSTOMERS WHERE FIRST_NAME BETWEEN 'B' AND 'C'; -- 5